local yamaha_Keyboard_PSR_220 = Instance.new("Model")
yamaha_Keyboard_PSR_220.Name = "Yamaha Keyboard PSR-220"
yamaha_Keyboard_PSR_220.WorldPivot = CFrame.new(18.7374878, 1.73387921, -69.7248077, 0, 0, -1, 0, -1, 0, -1, 0, 0)

local body = Instance.new("Model")
body.Name = "Body"
body.WorldPivot = CFrame.new(18.7374878, 3.15250921, -69.6901245, 0, 0, -1, 0, -1, 0, -1, 0, 0)

local part = Instance.new("Part")
part.Name = "Part"
part.Anchored = true
part.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part.BrickColor = BrickColor.new("Really black")
part.CFrame = CFrame.new(15.6181908, 3.11517882, -69.6818314, 0, 0, -1, 0, -1, 0, -1, 0, 0)
part.Color = Color3.fromRGB(17, 17, 17)
part.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part.Rotation = Vector3.new(-180, -90, 0)
part.Size = Vector3.new(2.35, 0.241, 0.166)
part.TopSurface = Enum.SurfaceType.SmoothNoOutlines
part.Parent = body

local part1 = Instance.new("Part")
part1.Name = "Part"
part1.Anchored = true
part1.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part1.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part1.BrickColor = BrickColor.new("Really black")
part1.CFrame = CFrame.new(21.8236446, 3.11517882, -69.6818314, 0, 0, -1, 0, -1, 0, -1, 0, 0)
part1.Color = Color3.fromRGB(17, 17, 17)
part1.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part1.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part1.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part1.Rotation = Vector3.new(-180, -90, 0)
part1.Size = Vector3.new(2.35, 0.241, 0.166)
part1.TopSurface = Enum.SurfaceType.SmoothNoOutlines
part1.Parent = body

local part2 = Instance.new("Part")
part2.Name = "Part"
part2.Anchored = true
part2.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part2.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part2.BrickColor = BrickColor.new("Really black")
part2.CFrame = CFrame.new(18.7250557, 3.06125474, -69.6652374, 0, 0, -1, 0, -1, 0, -1, 0, 0)
part2.Color = Color3.fromRGB(17, 17, 17)
part2.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part2.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part2.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part2.Rotation = Vector3.new(-180, -90, 0)
part2.Size = Vector3.new(2.31, 0.183, 6.36)
part2.TopSurface = Enum.SurfaceType.SmoothNoOutlines
part2.Parent = body

local part3 = Instance.new("Part")
part3.Name = "Part"
part3.Anchored = true
part3.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part3.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part3.BrickColor = BrickColor.new("Really black")
part3.CFrame = CFrame.new(18.7250557, 2.92851663, -69.6901321, 0, 0, -1, 0, -1, 0, -1, 0, 0)
part3.Color = Color3.fromRGB(17, 17, 17)
part3.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part3.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part3.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part3.Rotation = Vector3.new(-180, -90, 0)
part3.Size = Vector3.new(2.36, 0.183, 6.36)
part3.TopSurface = Enum.SurfaceType.SmoothNoOutlines
part3.Parent = body

local part4 = Instance.new("Part")
part4.Name = "Part"
part4.Anchored = true
part4.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part4.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part4.BrickColor = BrickColor.new("Really black")
part4.CFrame = CFrame.new(18.7085247, 3.1732471, -69.1716385, 1, 0, 0, 0, 1, 0, 0, 0, 1)
part4.Color = Color3.fromRGB(17, 17, 17)
part4.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part4.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part4.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part4.Size = Vector3.new(6.06, 0.241, 1.33)
part4.TopSurface = Enum.SurfaceType.SmoothNoOutlines
part4.Parent = body

local wedge = Instance.new("WedgePart")
wedge.Name = "Wedge"
wedge.Anchored = true
wedge.BackSurface = Enum.SurfaceType.SmoothNoOutlines
wedge.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
wedge.BrickColor = BrickColor.new("Really black")
wedge.CFrame = CFrame.new(20.5544071, 3.37650371, -69.1716385, 1, 0, 0, 0, 1, 0, 0, 0, 1)
wedge.Color = Color3.fromRGB(17, 17, 17)
wedge.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
wedge.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
wedge.Material = Enum.Material.SmoothPlastic
wedge.RightSurface = Enum.SurfaceType.SmoothNoOutlines
wedge.Size = Vector3.new(2.39, 0.166, 1.33)
wedge.TopSurface = Enum.SurfaceType.SmoothNoOutlines
wedge.Parent = body

local wedge1 = Instance.new("WedgePart")
wedge1.Name = "Wedge"
wedge1.Anchored = true
wedge1.BackSurface = Enum.SurfaceType.SmoothNoOutlines
wedge1.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
wedge1.BrickColor = BrickColor.new("Really black")
wedge1.CFrame = CFrame.new(21.9895496, 3.06125474, -69.6901321, -1.14624046e-10, 1, -3.65078506e-07, -1, -1.14624379e-10, -9.16994869e-10, -9.16994924e-10, 3.65078506e-07, 1)
wedge1.Color = Color3.fromRGB(17, 17, 17)
wedge1.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
wedge1.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
wedge1.Material = Enum.Material.SmoothPlastic
wedge1.RightSurface = Enum.SurfaceType.SmoothNoOutlines
wedge1.Rotation = Vector3.new(0, 0, -90)
wedge1.Size = Vector3.new(0.348, 0.166, 2.31)
wedge1.TopSurface = Enum.SurfaceType.SmoothNoOutlines
wedge1.Parent = body

local wedge2 = Instance.new("WedgePart")
wedge2.Name = "Wedge"
wedge2.Anchored = true
wedge2.BackSurface = Enum.SurfaceType.SmoothNoOutlines
wedge2.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
wedge2.BrickColor = BrickColor.new("Really black")
wedge2.CFrame = CFrame.new(15.485424, 3.06125474, -69.6901321, 1.14624046e-10, -1, -3.65078506e-07, 1, 1.14624379e-10, -9.16994869e-10, 9.16994924e-10, -3.65078506e-07, 1)
wedge2.Color = Color3.fromRGB(17, 17, 17)
wedge2.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
wedge2.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
wedge2.Material = Enum.Material.SmoothPlastic
wedge2.RightSurface = Enum.SurfaceType.SmoothNoOutlines
wedge2.Rotation = Vector3.new(0, 0, 90)
wedge2.Size = Vector3.new(0.348, 0.166, 2.31)
wedge2.TopSurface = Enum.SurfaceType.SmoothNoOutlines
wedge2.Parent = body

local wedge3 = Instance.new("WedgePart")
wedge3.Name = "Wedge"
wedge3.Anchored = true
wedge3.BackSurface = Enum.SurfaceType.SmoothNoOutlines
wedge3.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
wedge3.BrickColor = BrickColor.new("Really black")
wedge3.CFrame = CFrame.new(15.6181908, 3.25621033, -69.644516, 1, 0, 0, 0, 1, 0, 0, 0, 1)
wedge3.Color = Color3.fromRGB(17, 17, 17)
wedge3.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
wedge3.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
wedge3.Material = Enum.Material.SmoothPlastic
wedge3.RightSurface = Enum.SurfaceType.SmoothNoOutlines
wedge3.Size = Vector3.new(0.166, 0.257, 2.27)
wedge3.TopSurface = Enum.SurfaceType.SmoothNoOutlines
wedge3.Parent = body

local wedge4 = Instance.new("WedgePart")
wedge4.Name = "Wedge"
wedge4.Anchored = true
wedge4.BackSurface = Enum.SurfaceType.SmoothNoOutlines
wedge4.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
wedge4.BrickColor = BrickColor.new("Really black")
wedge4.CFrame = CFrame.new(21.8236694, 3.25621033, -69.644516, 1, 0, 0, 0, 1, 0, 0, 0, 1)
wedge4.Color = Color3.fromRGB(17, 17, 17)
wedge4.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
wedge4.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
wedge4.Material = Enum.Material.SmoothPlastic
wedge4.RightSurface = Enum.SurfaceType.SmoothNoOutlines
wedge4.Size = Vector3.new(0.166, 0.257, 2.27)
wedge4.TopSurface = Enum.SurfaceType.SmoothNoOutlines
wedge4.Parent = body

local wedge5 = Instance.new("WedgePart")
wedge5.Name = "Wedge"
wedge5.Anchored = true
wedge5.BackSurface = Enum.SurfaceType.SmoothNoOutlines
wedge5.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
wedge5.BrickColor = BrickColor.new("Really black")
wedge5.CFrame = CFrame.new(16.8875408, 3.37650371, -69.1716385, 1, 0, 0, 0, 1, 0, 0, 0, 1)
wedge5.Color = Color3.fromRGB(17, 17, 17)
wedge5.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
wedge5.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
wedge5.Material = Enum.Material.SmoothPlastic
wedge5.RightSurface = Enum.SurfaceType.SmoothNoOutlines
wedge5.Size = Vector3.new(2.42, 0.166, 1.33)
wedge5.TopSurface = Enum.SurfaceType.SmoothNoOutlines
wedge5.Parent = body

local wedge6 = Instance.new("WedgePart")
wedge6.Name = "Wedge"
wedge6.Anchored = true
wedge6.BackSurface = Enum.SurfaceType.SmoothNoOutlines
wedge6.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
wedge6.BrickColor = BrickColor.new("Really black")
wedge6.CFrame = CFrame.new(18.7292213, 3.3847971, -69.5366592, 1, 0, 0, 0, 1, 0, 0, 0, 1)
wedge6.Color = Color3.fromRGB(17, 17, 17)
wedge6.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
wedge6.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
wedge6.Material = Enum.Material.SmoothPlastic
wedge6.RightSurface = Enum.SurfaceType.SmoothNoOutlines
wedge6.Size = Vector3.new(1.26, 0.166, 0.597)
wedge6.TopSurface = Enum.SurfaceType.SmoothNoOutlines
wedge6.Parent = body

local part5 = Instance.new("Part")
part5.Name = "Part"
part5.Anchored = true
part5.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part5.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part5.BrickColor = BrickColor.new("Really black")
part5.CFrame = CFrame.new(18.7125874, 3.22717619, -68.8646698, 0, 0, -1, 0, -1, 0, -1, 0, 0)
part5.Color = Color3.fromRGB(17, 17, 17)
part5.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part5.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part5.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part5.Rotation = Vector3.new(-180, -90, 0)
part5.Size = Vector3.new(0.713, 0.183, 1.21)
part5.TopSurface = Enum.SurfaceType.SmoothNoOutlines
part5.Parent = body

local wedge7 = Instance.new("WedgePart")
wedge7.Name = "Wedge"
wedge7.Anchored = true
wedge7.BackSurface = Enum.SurfaceType.SmoothNoOutlines
wedge7.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
wedge7.BrickColor = BrickColor.new("Really black")
wedge7.CFrame = CFrame.new(18.7292213, 3.3847971, -69.163353, -1, 0, 0, 0, 1, 0, 0, 0, -1)
wedge7.Color = Color3.fromRGB(17, 17, 17)
wedge7.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
wedge7.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
wedge7.Material = Enum.Material.SmoothPlastic
wedge7.RightSurface = Enum.SurfaceType.SmoothNoOutlines
wedge7.Rotation = Vector3.new(-180, 0, -180)
wedge7.Size = Vector3.new(1.26, 0.166, 0.166)
wedge7.TopSurface = Enum.SurfaceType.SmoothNoOutlines
wedge7.Parent = body

local wedge8 = Instance.new("WedgePart")
wedge8.Name = "Wedge"
wedge8.Anchored = true
wedge8.BackSurface = Enum.SurfaceType.SmoothNoOutlines
wedge8.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
wedge8.BrickColor = BrickColor.new("Really black")
wedge8.CFrame = CFrame.new(18.7333794, 3.3847971, -68.8439255, 1, 0, 0, 0, 1, 0, 0, 0, 1)
wedge8.Color = Color3.fromRGB(17, 17, 17)
wedge8.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
wedge8.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
wedge8.Material = Enum.Material.SmoothPlastic
wedge8.RightSurface = Enum.SurfaceType.SmoothNoOutlines
wedge8.Size = Vector3.new(1.27, 0.166, 0.672)
wedge8.TopSurface = Enum.SurfaceType.SmoothNoOutlines
wedge8.Parent = body

local part6 = Instance.new("Part")
part6.Name = "Part"
part6.Anchored = true
part6.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part6.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part6.BrickColor = BrickColor.Black()
part6.CFrame = CFrame.new(18.720747, 3.23058915, -68.8340454, 1, 0, -0, 0, 0.99227792, 0.12403439, 0, -0.12403439, 0.99227792)
part6.Color = Color3.fromRGB(27, 42, 53)
part6.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part6.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part6.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part6.Rotation = Vector3.new(-7.12, 0, 0)
part6.Size = Vector3.new(0.508, 0.373, 0.548)
part6.TopSurface = Enum.SurfaceType.SmoothNoOutlines

local decal = Instance.new("Decal")
decal.Name = "Decal"
decal.Texture = "rbxassetid://7498708511"
decal.Face = Enum.NormalId.Top
decal.Parent = part6

part6.Parent = body

body.Parent = yamaha_Keyboard_PSR_220

local keys = Instance.new("Model")
keys.Name = "Keys"
keys.WorldPivot = CFrame.new(18.7168503, 3.14006686, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)

local keyset1 = Instance.new("Model")
keyset1.Name = "Keyset1"
keyset1.WorldPivot = CFrame.new(20.9816799, 3.14006686, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)

local a_ = Instance.new("Part")
a_.Name = "A#"
a_.Anchored = true
a_.BottomSurface = Enum.SurfaceType.Smooth
a_.BrickColor = BrickColor.new("Really black")
a_.CFrame = CFrame.new(20.4466362, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
a_.Color = Color3.fromRGB(17, 17, 17)
a_.Rotation = Vector3.new(0, 90, 0)
a_.Size = Vector3.new(0.498, 0.166, 0.166)
a_.TopSurface = Enum.SurfaceType.Smooth
a_.Parent = keyset1

local g_ = Instance.new("Part")
g_.Name = "G#"
g_.Anchored = true
g_.BottomSurface = Enum.SurfaceType.Smooth
g_.BrickColor = BrickColor.new("Really black")
g_.CFrame = CFrame.new(20.6623116, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
g_.Color = Color3.fromRGB(17, 17, 17)
g_.Rotation = Vector3.new(0, 90, 0)
g_.Size = Vector3.new(0.498, 0.166, 0.166)
g_.TopSurface = Enum.SurfaceType.Smooth
g_.Parent = keyset1

local f_ = Instance.new("Part")
f_.Name = "F#"
f_.Anchored = true
f_.BottomSurface = Enum.SurfaceType.Smooth
f_.BrickColor = BrickColor.new("Really black")
f_.CFrame = CFrame.new(20.8780117, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
f_.Color = Color3.fromRGB(17, 17, 17)
f_.Rotation = Vector3.new(0, 90, 0)
f_.Size = Vector3.new(0.498, 0.166, 0.166)
f_.TopSurface = Enum.SurfaceType.Smooth
f_.Parent = keyset1

local b = Instance.new("Part")
b.Name = "B"
b.Anchored = true
b.BottomSurface = Enum.SurfaceType.Smooth
b.BrickColor = BrickColor.new("Institutional white")
b.CFrame = CFrame.new(20.3346252, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
b.Color = Color3.fromRGB(248, 248, 248)
b.Rotation = Vector3.new(0, 90, 0)
b.Size = Vector3.new(0.996, 0.166, 0.207)
b.TopSurface = Enum.SurfaceType.Smooth
b.Parent = keyset1

local d_ = Instance.new("Part")
d_.Name = "D#"
d_.Anchored = true
d_.BottomSurface = Enum.SurfaceType.Smooth
d_.BrickColor = BrickColor.new("Really black")
d_.CFrame = CFrame.new(21.3093872, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
d_.Color = Color3.fromRGB(17, 17, 17)
d_.Rotation = Vector3.new(0, 90, 0)
d_.Size = Vector3.new(0.498, 0.166, 0.166)
d_.TopSurface = Enum.SurfaceType.Smooth
d_.Parent = keyset1

local f = Instance.new("Part")
f.Name = "F"
f.Anchored = true
f.BottomSurface = Enum.SurfaceType.Smooth
f.BrickColor = BrickColor.new("Institutional white")
f.CFrame = CFrame.new(20.9816742, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
f.Color = Color3.fromRGB(248, 248, 248)
f.Rotation = Vector3.new(0, 90, 0)
f.Size = Vector3.new(0.996, 0.166, 0.207)
f.TopSurface = Enum.SurfaceType.Smooth
f.Parent = keyset1

local e = Instance.new("Part")
e.Name = "E"
e.Anchored = true
e.BottomSurface = Enum.SurfaceType.Smooth
e.BrickColor = BrickColor.new("Institutional white")
e.CFrame = CFrame.new(21.1973743, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
e.Color = Color3.fromRGB(248, 248, 248)
e.Rotation = Vector3.new(0, 90, 0)
e.Size = Vector3.new(0.996, 0.166, 0.207)
e.TopSurface = Enum.SurfaceType.Smooth
e.Parent = keyset1

local a = Instance.new("Part")
a.Name = "A"
a.Anchored = true
a.BottomSurface = Enum.SurfaceType.Smooth
a.BrickColor = BrickColor.new("Institutional white")
a.CFrame = CFrame.new(20.550293, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
a.Color = Color3.fromRGB(248, 248, 248)
a.Rotation = Vector3.new(0, 90, 0)
a.Size = Vector3.new(0.996, 0.166, 0.207)
a.TopSurface = Enum.SurfaceType.Smooth
a.Parent = keyset1

local g = Instance.new("Part")
g.Name = "G"
g.Anchored = true
g.BottomSurface = Enum.SurfaceType.Smooth
g.BrickColor = BrickColor.new("Institutional white")
g.CFrame = CFrame.new(20.7659798, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
g.Color = Color3.fromRGB(248, 248, 248)
g.Rotation = Vector3.new(0, 90, 0)
g.Size = Vector3.new(0.996, 0.166, 0.207)
g.TopSurface = Enum.SurfaceType.Smooth
g.Parent = keyset1

local d = Instance.new("Part")
d.Name = "D"
d.Anchored = true
d.BottomSurface = Enum.SurfaceType.Smooth
d.BrickColor = BrickColor.new("Institutional white")
d.CFrame = CFrame.new(21.4130497, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
d.Color = Color3.fromRGB(248, 248, 248)
d.Rotation = Vector3.new(0, 90, 0)
d.Size = Vector3.new(0.996, 0.166, 0.207)
d.TopSurface = Enum.SurfaceType.Smooth
d.Parent = keyset1

local c_ = Instance.new("Part")
c_.Name = "C#"
c_.Anchored = true
c_.BottomSurface = Enum.SurfaceType.Smooth
c_.BrickColor = BrickColor.new("Really black")
c_.CFrame = CFrame.new(21.5250473, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
c_.Color = Color3.fromRGB(17, 17, 17)
c_.Rotation = Vector3.new(0, 90, 0)
c_.Size = Vector3.new(0.498, 0.166, 0.166)
c_.TopSurface = Enum.SurfaceType.Smooth
c_.Parent = keyset1

local c = Instance.new("Part")
c.Name = "C"
c.Anchored = true
c.BottomSurface = Enum.SurfaceType.Smooth
c.BrickColor = BrickColor.new("Institutional white")
c.CFrame = CFrame.new(21.6287365, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
c.Color = Color3.fromRGB(248, 248, 248)
c.Rotation = Vector3.new(0, 90, 0)
c.Size = Vector3.new(0.996, 0.166, 0.207)
c.TopSurface = Enum.SurfaceType.Smooth
c.Parent = keyset1

keyset1.Parent = keys

local keyset2 = Instance.new("Model")
keyset2.Name = "Keyset2"
keyset2.WorldPivot = CFrame.new(19.4717941, 3.14006686, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)

local a_1 = Instance.new("Part")
a_1.Name = "A#"
a_1.Anchored = true
a_1.BottomSurface = Enum.SurfaceType.Smooth
a_1.BrickColor = BrickColor.new("Really black")
a_1.CFrame = CFrame.new(18.9367504, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
a_1.Color = Color3.fromRGB(17, 17, 17)
a_1.Rotation = Vector3.new(0, 90, 0)
a_1.Size = Vector3.new(0.498, 0.166, 0.166)
a_1.TopSurface = Enum.SurfaceType.Smooth
a_1.Parent = keyset2

local g_1 = Instance.new("Part")
g_1.Name = "G#"
g_1.Anchored = true
g_1.BottomSurface = Enum.SurfaceType.Smooth
g_1.BrickColor = BrickColor.new("Really black")
g_1.CFrame = CFrame.new(19.1524239, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
g_1.Color = Color3.fromRGB(17, 17, 17)
g_1.Rotation = Vector3.new(0, 90, 0)
g_1.Size = Vector3.new(0.498, 0.166, 0.166)
g_1.TopSurface = Enum.SurfaceType.Smooth
g_1.Parent = keyset2

local f_1 = Instance.new("Part")
f_1.Name = "F#"
f_1.Anchored = true
f_1.BottomSurface = Enum.SurfaceType.Smooth
f_1.BrickColor = BrickColor.new("Really black")
f_1.CFrame = CFrame.new(19.368124, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
f_1.Color = Color3.fromRGB(17, 17, 17)
f_1.Rotation = Vector3.new(0, 90, 0)
f_1.Size = Vector3.new(0.498, 0.166, 0.166)
f_1.TopSurface = Enum.SurfaceType.Smooth
f_1.Parent = keyset2

local b1 = Instance.new("Part")
b1.Name = "B"
b1.Anchored = true
b1.BottomSurface = Enum.SurfaceType.Smooth
b1.BrickColor = BrickColor.new("Institutional white")
b1.CFrame = CFrame.new(18.8247375, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
b1.Color = Color3.fromRGB(248, 248, 248)
b1.Rotation = Vector3.new(0, 90, 0)
b1.Size = Vector3.new(0.996, 0.166, 0.207)
b1.TopSurface = Enum.SurfaceType.Smooth
b1.Parent = keyset2

local d_1 = Instance.new("Part")
d_1.Name = "D#"
d_1.Anchored = true
d_1.BottomSurface = Enum.SurfaceType.Smooth
d_1.BrickColor = BrickColor.new("Really black")
d_1.CFrame = CFrame.new(19.7994995, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
d_1.Color = Color3.fromRGB(17, 17, 17)
d_1.Rotation = Vector3.new(0, 90, 0)
d_1.Size = Vector3.new(0.498, 0.166, 0.166)
d_1.TopSurface = Enum.SurfaceType.Smooth
d_1.Parent = keyset2

local f1 = Instance.new("Part")
f1.Name = "F"
f1.Anchored = true
f1.BottomSurface = Enum.SurfaceType.Smooth
f1.BrickColor = BrickColor.new("Institutional white")
f1.CFrame = CFrame.new(19.4717884, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
f1.Color = Color3.fromRGB(248, 248, 248)
f1.Rotation = Vector3.new(0, 90, 0)
f1.Size = Vector3.new(0.996, 0.166, 0.207)
f1.TopSurface = Enum.SurfaceType.Smooth
f1.Parent = keyset2

local e1 = Instance.new("Part")
e1.Name = "E"
e1.Anchored = true
e1.BottomSurface = Enum.SurfaceType.Smooth
e1.BrickColor = BrickColor.new("Institutional white")
e1.CFrame = CFrame.new(19.6874886, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
e1.Color = Color3.fromRGB(248, 248, 248)
e1.Rotation = Vector3.new(0, 90, 0)
e1.Size = Vector3.new(0.996, 0.166, 0.207)
e1.TopSurface = Enum.SurfaceType.Smooth
e1.Parent = keyset2

local a1 = Instance.new("Part")
a1.Name = "A"
a1.Anchored = true
a1.BottomSurface = Enum.SurfaceType.Smooth
a1.BrickColor = BrickColor.new("Institutional white")
a1.CFrame = CFrame.new(19.0404072, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
a1.Color = Color3.fromRGB(248, 248, 248)
a1.Rotation = Vector3.new(0, 90, 0)
a1.Size = Vector3.new(0.996, 0.166, 0.207)
a1.TopSurface = Enum.SurfaceType.Smooth
a1.Parent = keyset2

local g1 = Instance.new("Part")
g1.Name = "G"
g1.Anchored = true
g1.BottomSurface = Enum.SurfaceType.Smooth
g1.BrickColor = BrickColor.new("Institutional white")
g1.CFrame = CFrame.new(19.256094, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
g1.Color = Color3.fromRGB(248, 248, 248)
g1.Rotation = Vector3.new(0, 90, 0)
g1.Size = Vector3.new(0.996, 0.166, 0.207)
g1.TopSurface = Enum.SurfaceType.Smooth
g1.Parent = keyset2

local d1 = Instance.new("Part")
d1.Name = "D"
d1.Anchored = true
d1.BottomSurface = Enum.SurfaceType.Smooth
d1.BrickColor = BrickColor.new("Institutional white")
d1.CFrame = CFrame.new(19.903162, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
d1.Color = Color3.fromRGB(248, 248, 248)
d1.Rotation = Vector3.new(0, 90, 0)
d1.Size = Vector3.new(0.996, 0.166, 0.207)
d1.TopSurface = Enum.SurfaceType.Smooth
d1.Parent = keyset2

local c_1 = Instance.new("Part")
c_1.Name = "C#"
c_1.Anchored = true
c_1.BottomSurface = Enum.SurfaceType.Smooth
c_1.BrickColor = BrickColor.new("Really black")
c_1.CFrame = CFrame.new(20.0151615, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
c_1.Color = Color3.fromRGB(17, 17, 17)
c_1.Rotation = Vector3.new(0, 90, 0)
c_1.Size = Vector3.new(0.498, 0.166, 0.166)
c_1.TopSurface = Enum.SurfaceType.Smooth
c_1.Parent = keyset2

local c1 = Instance.new("Part")
c1.Name = "C"
c1.Anchored = true
c1.BottomSurface = Enum.SurfaceType.Smooth
c1.BrickColor = BrickColor.new("Institutional white")
c1.CFrame = CFrame.new(20.1188507, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
c1.Color = Color3.fromRGB(248, 248, 248)
c1.Rotation = Vector3.new(0, 90, 0)
c1.Size = Vector3.new(0.996, 0.166, 0.207)
c1.TopSurface = Enum.SurfaceType.Smooth
c1.Parent = keyset2

keyset2.Parent = keys

local keyset3 = Instance.new("Model")
keyset3.Name = "Keyset3"
keyset3.WorldPivot = CFrame.new(17.9619083, 3.14006686, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)

local a_2 = Instance.new("Part")
a_2.Name = "A#"
a_2.Anchored = true
a_2.BottomSurface = Enum.SurfaceType.Smooth
a_2.BrickColor = BrickColor.new("Really black")
a_2.CFrame = CFrame.new(17.4268627, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
a_2.Color = Color3.fromRGB(17, 17, 17)
a_2.Rotation = Vector3.new(0, 90, 0)
a_2.Size = Vector3.new(0.498, 0.166, 0.166)
a_2.TopSurface = Enum.SurfaceType.Smooth
a_2.Parent = keyset3

local g_2 = Instance.new("Part")
g_2.Name = "G#"
g_2.Anchored = true
g_2.BottomSurface = Enum.SurfaceType.Smooth
g_2.BrickColor = BrickColor.new("Really black")
g_2.CFrame = CFrame.new(17.6425381, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
g_2.Color = Color3.fromRGB(17, 17, 17)
g_2.Rotation = Vector3.new(0, 90, 0)
g_2.Size = Vector3.new(0.498, 0.166, 0.166)
g_2.TopSurface = Enum.SurfaceType.Smooth
g_2.Parent = keyset3

local f_2 = Instance.new("Part")
f_2.Name = "F#"
f_2.Anchored = true
f_2.BottomSurface = Enum.SurfaceType.Smooth
f_2.BrickColor = BrickColor.new("Really black")
f_2.CFrame = CFrame.new(17.8582363, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
f_2.Color = Color3.fromRGB(17, 17, 17)
f_2.Rotation = Vector3.new(0, 90, 0)
f_2.Size = Vector3.new(0.498, 0.166, 0.166)
f_2.TopSurface = Enum.SurfaceType.Smooth
f_2.Parent = keyset3

local b2 = Instance.new("Part")
b2.Name = "B"
b2.Anchored = true
b2.BottomSurface = Enum.SurfaceType.Smooth
b2.BrickColor = BrickColor.new("Institutional white")
b2.CFrame = CFrame.new(17.3148518, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
b2.Color = Color3.fromRGB(248, 248, 248)
b2.Rotation = Vector3.new(0, 90, 0)
b2.Size = Vector3.new(0.996, 0.166, 0.207)
b2.TopSurface = Enum.SurfaceType.Smooth
b2.Parent = keyset3

local d_2 = Instance.new("Part")
d_2.Name = "D#"
d_2.Anchored = true
d_2.BottomSurface = Enum.SurfaceType.Smooth
d_2.BrickColor = BrickColor.new("Really black")
d_2.CFrame = CFrame.new(18.2896099, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
d_2.Color = Color3.fromRGB(17, 17, 17)
d_2.Rotation = Vector3.new(0, 90, 0)
d_2.Size = Vector3.new(0.498, 0.166, 0.166)
d_2.TopSurface = Enum.SurfaceType.Smooth
d_2.Parent = keyset3

local f2 = Instance.new("Part")
f2.Name = "F"
f2.Anchored = true
f2.BottomSurface = Enum.SurfaceType.Smooth
f2.BrickColor = BrickColor.new("Institutional white")
f2.CFrame = CFrame.new(17.9618988, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
f2.Color = Color3.fromRGB(248, 248, 248)
f2.Rotation = Vector3.new(0, 90, 0)
f2.Size = Vector3.new(0.996, 0.166, 0.207)
f2.TopSurface = Enum.SurfaceType.Smooth
f2.Parent = keyset3

local e2 = Instance.new("Part")
e2.Name = "E"
e2.Anchored = true
e2.BottomSurface = Enum.SurfaceType.Smooth
e2.BrickColor = BrickColor.new("Institutional white")
e2.CFrame = CFrame.new(18.177599, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
e2.Color = Color3.fromRGB(248, 248, 248)
e2.Rotation = Vector3.new(0, 90, 0)
e2.Size = Vector3.new(0.996, 0.166, 0.207)
e2.TopSurface = Enum.SurfaceType.Smooth
e2.Parent = keyset3

local a2 = Instance.new("Part")
a2.Name = "A"
a2.Anchored = true
a2.BottomSurface = Enum.SurfaceType.Smooth
a2.BrickColor = BrickColor.new("Institutional white")
a2.CFrame = CFrame.new(17.5305214, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
a2.Color = Color3.fromRGB(248, 248, 248)
a2.Rotation = Vector3.new(0, 90, 0)
a2.Size = Vector3.new(0.996, 0.166, 0.207)
a2.TopSurface = Enum.SurfaceType.Smooth
a2.Parent = keyset3

local g2 = Instance.new("Part")
g2.Name = "G"
g2.Anchored = true
g2.BottomSurface = Enum.SurfaceType.Smooth
g2.BrickColor = BrickColor.new("Institutional white")
g2.CFrame = CFrame.new(17.7462082, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
g2.Color = Color3.fromRGB(248, 248, 248)
g2.Rotation = Vector3.new(0, 90, 0)
g2.Size = Vector3.new(0.996, 0.166, 0.207)
g2.TopSurface = Enum.SurfaceType.Smooth
g2.Parent = keyset3

local d2 = Instance.new("Part")
d2.Name = "D"
d2.Anchored = true
d2.BottomSurface = Enum.SurfaceType.Smooth
d2.BrickColor = BrickColor.new("Institutional white")
d2.CFrame = CFrame.new(18.3932724, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
d2.Color = Color3.fromRGB(248, 248, 248)
d2.Rotation = Vector3.new(0, 90, 0)
d2.Size = Vector3.new(0.996, 0.166, 0.207)
d2.TopSurface = Enum.SurfaceType.Smooth
d2.Parent = keyset3

local c_2 = Instance.new("Part")
c_2.Name = "C#"
c_2.Anchored = true
c_2.BottomSurface = Enum.SurfaceType.Smooth
c_2.BrickColor = BrickColor.new("Really black")
c_2.CFrame = CFrame.new(18.5052757, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
c_2.Color = Color3.fromRGB(17, 17, 17)
c_2.Rotation = Vector3.new(0, 90, 0)
c_2.Size = Vector3.new(0.498, 0.166, 0.166)
c_2.TopSurface = Enum.SurfaceType.Smooth
c_2.Parent = keyset3

local c2 = Instance.new("Part")
c2.Name = "C"
c2.Anchored = true
c2.BottomSurface = Enum.SurfaceType.Smooth
c2.BrickColor = BrickColor.new("Institutional white")
c2.CFrame = CFrame.new(18.608963, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
c2.Color = Color3.fromRGB(248, 248, 248)
c2.Rotation = Vector3.new(0, 90, 0)
c2.Size = Vector3.new(0.996, 0.166, 0.207)
c2.TopSurface = Enum.SurfaceType.Smooth
c2.Parent = keyset3

keyset3.Parent = keys

local keyset4 = Instance.new("Model")
keyset4.Name = "Keyset4"
keyset4.WorldPivot = CFrame.new(16.4520206, 3.14006686, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)

local a_3 = Instance.new("Part")
a_3.Name = "A#"
a_3.Anchored = true
a_3.BottomSurface = Enum.SurfaceType.Smooth
a_3.BrickColor = BrickColor.new("Really black")
a_3.CFrame = CFrame.new(15.9169769, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
a_3.Color = Color3.fromRGB(17, 17, 17)
a_3.Rotation = Vector3.new(0, 90, 0)
a_3.Size = Vector3.new(0.498, 0.166, 0.166)
a_3.TopSurface = Enum.SurfaceType.Smooth
a_3.Parent = keyset4

local g_3 = Instance.new("Part")
g_3.Name = "G#"
g_3.Anchored = true
g_3.BottomSurface = Enum.SurfaceType.Smooth
g_3.BrickColor = BrickColor.new("Really black")
g_3.CFrame = CFrame.new(16.1326523, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
g_3.Color = Color3.fromRGB(17, 17, 17)
g_3.Rotation = Vector3.new(0, 90, 0)
g_3.Size = Vector3.new(0.498, 0.166, 0.166)
g_3.TopSurface = Enum.SurfaceType.Smooth
g_3.Parent = keyset4

local f_3 = Instance.new("Part")
f_3.Name = "F#"
f_3.Anchored = true
f_3.BottomSurface = Enum.SurfaceType.Smooth
f_3.BrickColor = BrickColor.new("Really black")
f_3.CFrame = CFrame.new(16.3483486, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
f_3.Color = Color3.fromRGB(17, 17, 17)
f_3.Rotation = Vector3.new(0, 90, 0)
f_3.Size = Vector3.new(0.498, 0.166, 0.166)
f_3.TopSurface = Enum.SurfaceType.Smooth
f_3.Parent = keyset4

local b3 = Instance.new("Part")
b3.Name = "B"
b3.Anchored = true
b3.BottomSurface = Enum.SurfaceType.Smooth
b3.BrickColor = BrickColor.new("Institutional white")
b3.CFrame = CFrame.new(15.804965, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
b3.Color = Color3.fromRGB(248, 248, 248)
b3.Rotation = Vector3.new(0, 90, 0)
b3.Size = Vector3.new(0.996, 0.166, 0.207)
b3.TopSurface = Enum.SurfaceType.Smooth
b3.Parent = keyset4

local d_3 = Instance.new("Part")
d_3.Name = "D#"
d_3.Anchored = true
d_3.BottomSurface = Enum.SurfaceType.Smooth
d_3.BrickColor = BrickColor.new("Really black")
d_3.CFrame = CFrame.new(16.7797241, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
d_3.Color = Color3.fromRGB(17, 17, 17)
d_3.Rotation = Vector3.new(0, 90, 0)
d_3.Size = Vector3.new(0.498, 0.166, 0.166)
d_3.TopSurface = Enum.SurfaceType.Smooth
d_3.Parent = keyset4

local f3 = Instance.new("Part")
f3.Name = "F"
f3.Anchored = true
f3.BottomSurface = Enum.SurfaceType.Smooth
f3.BrickColor = BrickColor.new("Institutional white")
f3.CFrame = CFrame.new(16.4520149, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
f3.Color = Color3.fromRGB(248, 248, 248)
f3.Rotation = Vector3.new(0, 90, 0)
f3.Size = Vector3.new(0.996, 0.166, 0.207)
f3.TopSurface = Enum.SurfaceType.Smooth
f3.Parent = keyset4

local e3 = Instance.new("Part")
e3.Name = "E"
e3.Anchored = true
e3.BottomSurface = Enum.SurfaceType.Smooth
e3.BrickColor = BrickColor.new("Institutional white")
e3.CFrame = CFrame.new(16.6677132, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
e3.Color = Color3.fromRGB(248, 248, 248)
e3.Rotation = Vector3.new(0, 90, 0)
e3.Size = Vector3.new(0.996, 0.166, 0.207)
e3.TopSurface = Enum.SurfaceType.Smooth
e3.Parent = keyset4

local a3 = Instance.new("Part")
a3.Name = "A"
a3.Anchored = true
a3.BottomSurface = Enum.SurfaceType.Smooth
a3.BrickColor = BrickColor.new("Institutional white")
a3.CFrame = CFrame.new(16.0206337, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
a3.Color = Color3.fromRGB(248, 248, 248)
a3.Rotation = Vector3.new(0, 90, 0)
a3.Size = Vector3.new(0.996, 0.166, 0.207)
a3.TopSurface = Enum.SurfaceType.Smooth
a3.Parent = keyset4

local g3 = Instance.new("Part")
g3.Name = "G"
g3.Anchored = true
g3.BottomSurface = Enum.SurfaceType.Smooth
g3.BrickColor = BrickColor.new("Institutional white")
g3.CFrame = CFrame.new(16.2363205, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
g3.Color = Color3.fromRGB(248, 248, 248)
g3.Rotation = Vector3.new(0, 90, 0)
g3.Size = Vector3.new(0.996, 0.166, 0.207)
g3.TopSurface = Enum.SurfaceType.Smooth
g3.Parent = keyset4

local d3 = Instance.new("Part")
d3.Name = "D"
d3.Anchored = true
d3.BottomSurface = Enum.SurfaceType.Smooth
d3.BrickColor = BrickColor.new("Institutional white")
d3.CFrame = CFrame.new(16.8833885, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
d3.Color = Color3.fromRGB(248, 248, 248)
d3.Rotation = Vector3.new(0, 90, 0)
d3.Size = Vector3.new(0.996, 0.166, 0.207)
d3.TopSurface = Enum.SurfaceType.Smooth
d3.Parent = keyset4

local c_3 = Instance.new("Part")
c_3.Name = "C#"
c_3.Anchored = true
c_3.BottomSurface = Enum.SurfaceType.Smooth
c_3.BrickColor = BrickColor.new("Really black")
c_3.CFrame = CFrame.new(16.995388, 3.16910195, -70.0842056, 0, 0, 1, 0, 1, 0, -1, 0, 0)
c_3.Color = Color3.fromRGB(17, 17, 17)
c_3.Rotation = Vector3.new(0, 90, 0)
c_3.Size = Vector3.new(0.498, 0.166, 0.166)
c_3.TopSurface = Enum.SurfaceType.Smooth
c_3.Parent = keyset4

local c3 = Instance.new("Part")
c3.Name = "C"
c3.Anchored = true
c3.BottomSurface = Enum.SurfaceType.Smooth
c3.BrickColor = BrickColor.new("Institutional white")
c3.CFrame = CFrame.new(17.0990753, 3.13591862, -70.3330841, 0, 0, 1, 0, 1, 0, -1, 0, 0)
c3.Color = Color3.fromRGB(248, 248, 248)
c3.Rotation = Vector3.new(0, 90, 0)
c3.Size = Vector3.new(0.996, 0.166, 0.207)
c3.TopSurface = Enum.SurfaceType.Smooth
c3.Parent = keyset4

keyset4.Parent = keys

keys.Parent = yamaha_Keyboard_PSR_220

local stand = Instance.new("Model")
stand.Name = "Stand"
stand.WorldPivot = CFrame.new(18.7196198, 1.43522274, -69.7677917, 0.426958978, 0.904271007, 0, 0.904271007, -0.426958978, 0, -0, 0, -1)

local part7 = Instance.new("Part")
part7.Name = "Part"
part7.Anchored = true
part7.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part7.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part7.BrickColor = BrickColor.new("Really black")
part7.CFrame = CFrame.new(18.7003536, 1.44661319, -70.196991, -0.431978375, 0.901884079, 0, 0.901884079, 0.431978375, 0, 0, -0, -1)
part7.Color = Color3.fromRGB(17, 17, 17)
part7.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part7.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part7.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part7.Rotation = Vector3.new(-180, 0, -116)
part7.Size = Vector3.new(0.166, 6.02, 0.166)
part7.TopSurface = Enum.SurfaceType.SmoothNoOutlines
part7.Parent = stand

local part8 = Instance.new("Part")
part8.Name = "Part"
part8.Anchored = true
part8.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part8.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part8.BrickColor = BrickColor.new("Really black")
part8.CFrame = CFrame.new(18.7003536, 1.44661319, -70.196991, 0.426958978, 0.904271007, 0, 0.904271007, -0.426958978, 0, -0, 0, -1)
part8.Color = Color3.fromRGB(17, 17, 17)
part8.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part8.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part8.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part8.Rotation = Vector3.new(-180, 0, -64.7)
part8.Size = Vector3.new(0.166, 6.02, 0.166)
part8.TopSurface = Enum.SurfaceType.SmoothNoOutlines
part8.Parent = stand

local part9 = Instance.new("Part")
part9.Name = "Part"
part9.Anchored = true
part9.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part9.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part9.BrickColor = BrickColor.new("Really black")
part9.CFrame = CFrame.new(18.7003536, 1.44661319, -69.3259048, 0.426958978, 0.904271007, 0, 0.904271007, -0.426958978, 0, -0, 0, -1)
part9.Color = Color3.fromRGB(17, 17, 17)
part9.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part9.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part9.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part9.Rotation = Vector3.new(-180, 0, -64.7)
part9.Size = Vector3.new(0.166, 6.02, 0.166)
part9.TopSurface = Enum.SurfaceType.SmoothNoOutlines
part9.Parent = stand

local part10 = Instance.new("Part")
part10.Name = "Part"
part10.Anchored = true
part10.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part10.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part10.BrickColor = BrickColor.new("Really black")
part10.CFrame = CFrame.new(18.7003536, 1.44661319, -69.3259048, -0.431978375, 0.901884079, 0, 0.901884079, 0.431978375, 0, 0, -0, -1)
part10.Color = Color3.fromRGB(17, 17, 17)
part10.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part10.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part10.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part10.Rotation = Vector3.new(-180, 0, -116)
part10.Size = Vector3.new(0.166, 6.02, 0.166)
part10.TopSurface = Enum.SurfaceType.SmoothNoOutlines
part10.Parent = stand

local part11 = Instance.new("Part")
part11.Name = "Part"
part11.Anchored = true
part11.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part11.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part11.BrickColor = BrickColor.new("Really black")
part11.CFrame = CFrame.new(21.4365883, 0.145181537, -68.7266464, 0, 0, 1, 1, 0, 0, 0, 1, 0)
part11.Color = Color3.fromRGB(17, 17, 17)
part11.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part11.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part11.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part11.Rotation = Vector3.new(90, 90, 0)
part11.Size = Vector3.new(0.29, 0.265, 0.29)
part11.TopSurface = Enum.SurfaceType.SmoothNoOutlines

local mesh = Instance.new("CylinderMesh")
mesh.Name = "Mesh"
mesh.Parent = part11

part11.Parent = stand

local part12 = Instance.new("Part")
part12.Name = "Part"
part12.Anchored = true
part12.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part12.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part12.BrickColor = BrickColor.new("Really black")
part12.CFrame = CFrame.new(21.4407406, 0.141033649, -69.80513, 0, 0, 1, 1, 0, 0, 0, 1, 0)
part12.Color = Color3.fromRGB(17, 17, 17)
part12.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part12.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part12.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part12.Rotation = Vector3.new(90, 90, 0)
part12.Size = Vector3.new(0.249, 2.19, 0.232)
part12.TopSurface = Enum.SurfaceType.SmoothNoOutlines

local mesh1 = Instance.new("CylinderMesh")
mesh1.Name = "Mesh"
mesh1.Parent = part12

part12.Parent = stand

local part13 = Instance.new("Part")
part13.Name = "Part"
part13.Anchored = true
part13.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part13.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part13.BrickColor = BrickColor.new("Really black")
part13.CFrame = CFrame.new(21.4365883, 0.145181537, -70.8089447, 0, 0, 1, 1, 0, 0, 0, 1, 0)
part13.Color = Color3.fromRGB(17, 17, 17)
part13.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part13.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part13.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part13.Rotation = Vector3.new(90, 90, 0)
part13.Size = Vector3.new(0.29, 0.265, 0.29)
part13.TopSurface = Enum.SurfaceType.SmoothNoOutlines

local mesh2 = Instance.new("CylinderMesh")
mesh2.Name = "Mesh"
mesh2.Parent = part13

part13.Parent = stand

local part14 = Instance.new("Part")
part14.Name = "Part"
part14.Anchored = true
part14.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part14.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part14.BrickColor = BrickColor.new("Really black")
part14.CFrame = CFrame.new(16.0026512, 0.145181537, -68.7266464, 0, 0, 1, 1, 0, 0, 0, 1, 0)
part14.Color = Color3.fromRGB(17, 17, 17)
part14.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part14.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part14.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part14.Rotation = Vector3.new(90, 90, 0)
part14.Size = Vector3.new(0.29, 0.265, 0.29)
part14.TopSurface = Enum.SurfaceType.SmoothNoOutlines

local mesh3 = Instance.new("CylinderMesh")
mesh3.Name = "Mesh"
mesh3.Parent = part14

part14.Parent = stand

local part15 = Instance.new("Part")
part15.Name = "Part"
part15.Anchored = true
part15.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part15.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part15.BrickColor = BrickColor.new("Really black")
part15.CFrame = CFrame.new(16.0068035, 0.141033649, -69.80513, 0, 0, 1, 1, 0, 0, 0, 1, 0)
part15.Color = Color3.fromRGB(17, 17, 17)
part15.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part15.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part15.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part15.Rotation = Vector3.new(90, 90, 0)
part15.Size = Vector3.new(0.249, 2.19, 0.232)
part15.TopSurface = Enum.SurfaceType.SmoothNoOutlines

local mesh4 = Instance.new("CylinderMesh")
mesh4.Name = "Mesh"
mesh4.Parent = part15

part15.Parent = stand

local part16 = Instance.new("Part")
part16.Name = "Part"
part16.Anchored = true
part16.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part16.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part16.BrickColor = BrickColor.new("Really black")
part16.CFrame = CFrame.new(16.0026512, 0.145181537, -70.8089447, 0, 0, 1, 1, 0, 0, 0, 1, 0)
part16.Color = Color3.fromRGB(17, 17, 17)
part16.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part16.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part16.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part16.Rotation = Vector3.new(90, 90, 0)
part16.Size = Vector3.new(0.29, 0.265, 0.29)
part16.TopSurface = Enum.SurfaceType.SmoothNoOutlines

local mesh5 = Instance.new("CylinderMesh")
mesh5.Name = "Mesh"
mesh5.Parent = part16

part16.Parent = stand

local part17 = Instance.new("Part")
part17.Name = "Part"
part17.Anchored = true
part17.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part17.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part17.BrickColor = BrickColor.new("Really black")
part17.CFrame = CFrame.new(16.0026512, 2.72526407, -68.7266464, 0, 0, 1, 1, 0, 0, 0, 1, 0)
part17.Color = Color3.fromRGB(17, 17, 17)
part17.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part17.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part17.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part17.Rotation = Vector3.new(90, 90, 0)
part17.Size = Vector3.new(0.29, 0.265, 0.29)
part17.TopSurface = Enum.SurfaceType.SmoothNoOutlines

local mesh6 = Instance.new("CylinderMesh")
mesh6.Name = "Mesh"
mesh6.Parent = part17

part17.Parent = stand

local part18 = Instance.new("Part")
part18.Name = "Part"
part18.Anchored = true
part18.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part18.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part18.BrickColor = BrickColor.new("Really black")
part18.CFrame = CFrame.new(16.0068035, 2.72111607, -69.80513, 0, 0, 1, 1, 0, 0, 0, 1, 0)
part18.Color = Color3.fromRGB(17, 17, 17)
part18.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part18.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part18.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part18.Rotation = Vector3.new(90, 90, 0)
part18.Size = Vector3.new(0.249, 2.19, 0.232)
part18.TopSurface = Enum.SurfaceType.SmoothNoOutlines

local mesh7 = Instance.new("CylinderMesh")
mesh7.Name = "Mesh"
mesh7.Parent = part18

part18.Parent = stand

local part19 = Instance.new("Part")
part19.Name = "Part"
part19.Anchored = true
part19.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part19.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part19.BrickColor = BrickColor.new("Really black")
part19.CFrame = CFrame.new(16.0026512, 2.72526407, -70.8089447, 0, 0, 1, 1, 0, 0, 0, 1, 0)
part19.Color = Color3.fromRGB(17, 17, 17)
part19.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part19.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part19.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part19.Rotation = Vector3.new(90, 90, 0)
part19.Size = Vector3.new(0.29, 0.265, 0.29)
part19.TopSurface = Enum.SurfaceType.SmoothNoOutlines

local mesh8 = Instance.new("CylinderMesh")
mesh8.Name = "Mesh"
mesh8.Parent = part19

part19.Parent = stand

local part20 = Instance.new("Part")
part20.Name = "Part"
part20.Anchored = true
part20.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part20.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part20.BrickColor = BrickColor.new("Really black")
part20.CFrame = CFrame.new(21.4365883, 2.72526407, -68.7266464, 0, 0, 1, 1, 0, 0, 0, 1, 0)
part20.Color = Color3.fromRGB(17, 17, 17)
part20.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part20.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part20.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part20.Rotation = Vector3.new(90, 90, 0)
part20.Size = Vector3.new(0.29, 0.265, 0.29)
part20.TopSurface = Enum.SurfaceType.SmoothNoOutlines

local mesh9 = Instance.new("CylinderMesh")
mesh9.Name = "Mesh"
mesh9.Parent = part20

part20.Parent = stand

local part21 = Instance.new("Part")
part21.Name = "Part"
part21.Anchored = true
part21.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part21.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part21.BrickColor = BrickColor.new("Really black")
part21.CFrame = CFrame.new(21.4407406, 2.72111607, -69.80513, 0, 0, 1, 1, 0, 0, 0, 1, 0)
part21.Color = Color3.fromRGB(17, 17, 17)
part21.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part21.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part21.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part21.Rotation = Vector3.new(90, 90, 0)
part21.Size = Vector3.new(0.249, 2.19, 0.232)
part21.TopSurface = Enum.SurfaceType.SmoothNoOutlines

local mesh10 = Instance.new("CylinderMesh")
mesh10.Name = "Mesh"
mesh10.Parent = part21

part21.Parent = stand

local part22 = Instance.new("Part")
part22.Name = "Part"
part22.Anchored = true
part22.BackSurface = Enum.SurfaceType.SmoothNoOutlines
part22.BottomSurface = Enum.SurfaceType.SmoothNoOutlines
part22.BrickColor = BrickColor.new("Really black")
part22.CFrame = CFrame.new(21.4365883, 2.72526407, -70.8089447, 0, 0, 1, 1, 0, 0, 0, 1, 0)
part22.Color = Color3.fromRGB(17, 17, 17)
part22.FrontSurface = Enum.SurfaceType.SmoothNoOutlines
part22.LeftSurface = Enum.SurfaceType.SmoothNoOutlines
part22.RightSurface = Enum.SurfaceType.SmoothNoOutlines
part22.Rotation = Vector3.new(90, 90, 0)
part22.Size = Vector3.new(0.29, 0.265, 0.29)
part22.TopSurface = Enum.SurfaceType.SmoothNoOutlines

local mesh11 = Instance.new("CylinderMesh")
mesh11.Name = "Mesh"
mesh11.Parent = part22

part22.Parent = stand

stand.Parent = yamaha_Keyboard_PSR_220

return yamaha_Keyboard_PSR_220
