local keys = Instance.new("Model")
keys.Name = "Keys"
keys.WorldPivot = CFrame.new(10.5925684, 0.200007439, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)

local keyset4 = Instance.new("Model")
keyset4.Name = "Keyset4"
keyset4.WorldPivot = CFrame.new(9.29261112, 0.2000103, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)

local key1 = Instance.new("Part")
key1.Name = "Key1"
key1.Anchored = true
key1.BottomSurface = Enum.SurfaceType.Smooth
key1.BrickColor = BrickColor.White()
key1.CFrame = CFrame.new(9.89261627, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key1.CanCollide = false
key1.Color = Color3.fromRGB(242, 243, 243)
key1.Material = Enum.Material.SmoothPlastic
key1.Rotation = Vector3.new(-180, 0, -180)
key1.Size = Vector3.new(0.2, 0.2, 1.2)
key1.TopSurface = Enum.SurfaceType.Smooth

local mesh = Instance.new("BlockMesh")
mesh.Name = "Mesh"
mesh.Parent = key1

key1.Parent = keyset4

local key2 = Instance.new("Part")
key2.Name = "Key2"
key2.Anchored = true
key2.BottomSurface = Enum.SurfaceType.Smooth
key2.BrickColor = BrickColor.new("Really black")
key2.CFrame = CFrame.new(9.79261017, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key2.CanCollide = false
key2.Color = Color3.fromRGB(17, 17, 17)
key2.Material = Enum.Material.SmoothPlastic
key2.Rotation = Vector3.new(-180, 0, -180)
key2.Size = Vector3.new(0.2, 0.2, 0.8)
key2.TopSurface = Enum.SurfaceType.Smooth

local mesh1 = Instance.new("BlockMesh")
mesh1.Name = "Mesh"
mesh1.Offset = Vector3.new(-0.02, -0.1, 0)
mesh1.Scale = Vector3.new(0.6, 1, 1)
mesh1.Parent = key2

key2.Parent = keyset4

local key3 = Instance.new("Part")
key3.Name = "Key3"
key3.Anchored = true
key3.BottomSurface = Enum.SurfaceType.Smooth
key3.BrickColor = BrickColor.White()
key3.CFrame = CFrame.new(9.69260406, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key3.CanCollide = false
key3.Color = Color3.fromRGB(242, 243, 243)
key3.Material = Enum.Material.SmoothPlastic
key3.Rotation = Vector3.new(-180, 0, -180)
key3.Size = Vector3.new(0.2, 0.2, 1.2)
key3.TopSurface = Enum.SurfaceType.Smooth

local mesh2 = Instance.new("BlockMesh")
mesh2.Name = "Mesh"
mesh2.Parent = key3

key3.Parent = keyset4

local key4 = Instance.new("Part")
key4.Name = "Key4"
key4.Anchored = true
key4.BottomSurface = Enum.SurfaceType.Smooth
key4.BrickColor = BrickColor.new("Really black")
key4.CFrame = CFrame.new(9.5925684, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key4.CanCollide = false
key4.Color = Color3.fromRGB(17, 17, 17)
key4.Material = Enum.Material.SmoothPlastic
key4.Rotation = Vector3.new(-180, 0, -180)
key4.Size = Vector3.new(0.2, 0.2, 0.8)
key4.TopSurface = Enum.SurfaceType.Smooth

local mesh3 = Instance.new("BlockMesh")
mesh3.Name = "Mesh"
mesh3.Offset = Vector3.new(0.02, -0.1, 0)
mesh3.Scale = Vector3.new(0.6, 1, 1)
mesh3.Parent = key4

key4.Parent = keyset4

local key5 = Instance.new("Part")
key5.Name = "Key5"
key5.Anchored = true
key5.BottomSurface = Enum.SurfaceType.Smooth
key5.BrickColor = BrickColor.White()
key5.CFrame = CFrame.new(9.49256229, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key5.CanCollide = false
key5.Color = Color3.fromRGB(242, 243, 243)
key5.Material = Enum.Material.SmoothPlastic
key5.Rotation = Vector3.new(-180, 0, -180)
key5.Size = Vector3.new(0.2, 0.2, 1.2)
key5.TopSurface = Enum.SurfaceType.Smooth

local mesh4 = Instance.new("BlockMesh")
mesh4.Name = "Mesh"
mesh4.Parent = key5

key5.Parent = keyset4

local key6 = Instance.new("Part")
key6.Name = "Key6"
key6.Anchored = true
key6.BottomSurface = Enum.SurfaceType.Smooth
key6.BrickColor = BrickColor.White()
key6.CFrame = CFrame.new(9.29261017, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key6.CanCollide = false
key6.Color = Color3.fromRGB(242, 243, 243)
key6.Material = Enum.Material.SmoothPlastic
key6.Rotation = Vector3.new(-180, 0, -180)
key6.Size = Vector3.new(0.2, 0.2, 1.2)
key6.TopSurface = Enum.SurfaceType.Smooth

local mesh5 = Instance.new("BlockMesh")
mesh5.Name = "Mesh"
mesh5.Parent = key6

key6.Parent = keyset4

local key7 = Instance.new("Part")
key7.Name = "Key7"
key7.Anchored = true
key7.BottomSurface = Enum.SurfaceType.Smooth
key7.BrickColor = BrickColor.new("Really black")
key7.CFrame = CFrame.new(9.19260406, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key7.CanCollide = false
key7.Color = Color3.fromRGB(17, 17, 17)
key7.Material = Enum.Material.SmoothPlastic
key7.Rotation = Vector3.new(-180, 0, -180)
key7.Size = Vector3.new(0.2, 0.2, 0.8)
key7.TopSurface = Enum.SurfaceType.Smooth

local mesh6 = Instance.new("BlockMesh")
mesh6.Name = "Mesh"
mesh6.Offset = Vector3.new(-0.02, -0.1, 0)
mesh6.Scale = Vector3.new(0.6, 1, 1)
mesh6.Parent = key7

key7.Parent = keyset4

local key8 = Instance.new("Part")
key8.Name = "Key8"
key8.Anchored = true
key8.BottomSurface = Enum.SurfaceType.Smooth
key8.BrickColor = BrickColor.White()
key8.CFrame = CFrame.new(9.09259796, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key8.CanCollide = false
key8.Color = Color3.fromRGB(242, 243, 243)
key8.Material = Enum.Material.SmoothPlastic
key8.Rotation = Vector3.new(-180, 0, -180)
key8.Size = Vector3.new(0.2, 0.2, 1.2)
key8.TopSurface = Enum.SurfaceType.Smooth

local mesh7 = Instance.new("BlockMesh")
mesh7.Name = "Mesh"
mesh7.Parent = key8

key8.Parent = keyset4

local key9 = Instance.new("Part")
key9.Name = "Key9"
key9.Anchored = true
key9.BottomSurface = Enum.SurfaceType.Smooth
key9.BrickColor = BrickColor.new("Really black")
key9.CFrame = CFrame.new(8.99256229, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key9.CanCollide = false
key9.Color = Color3.fromRGB(17, 17, 17)
key9.Material = Enum.Material.SmoothPlastic
key9.Rotation = Vector3.new(-180, 0, -180)
key9.Size = Vector3.new(0.2, 0.2, 0.8)
key9.TopSurface = Enum.SurfaceType.Smooth

local mesh8 = Instance.new("BlockMesh")
mesh8.Name = "Mesh"
mesh8.Offset = Vector3.new(0, -0.1, 0)
mesh8.Scale = Vector3.new(0.6, 1, 1)
mesh8.Parent = key9

key9.Parent = keyset4

local key10 = Instance.new("Part")
key10.Name = "Key10"
key10.Anchored = true
key10.BottomSurface = Enum.SurfaceType.Smooth
key10.BrickColor = BrickColor.White()
key10.CFrame = CFrame.new(8.89252567, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key10.CanCollide = false
key10.Color = Color3.fromRGB(242, 243, 243)
key10.Material = Enum.Material.SmoothPlastic
key10.Rotation = Vector3.new(-180, 0, -180)
key10.Size = Vector3.new(0.2, 0.2, 1.2)
key10.TopSurface = Enum.SurfaceType.Smooth

local mesh9 = Instance.new("BlockMesh")
mesh9.Name = "Mesh"
mesh9.Parent = key10

key10.Parent = keyset4

local key11 = Instance.new("Part")
key11.Name = "Key11"
key11.Anchored = true
key11.BottomSurface = Enum.SurfaceType.Smooth
key11.BrickColor = BrickColor.new("Really black")
key11.CFrame = CFrame.new(8.79255009, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key11.CanCollide = false
key11.Color = Color3.fromRGB(17, 17, 17)
key11.Material = Enum.Material.SmoothPlastic
key11.Rotation = Vector3.new(-180, 0, -180)
key11.Size = Vector3.new(0.2, 0.2, 0.8)
key11.TopSurface = Enum.SurfaceType.Smooth

local mesh10 = Instance.new("BlockMesh")
mesh10.Name = "Mesh"
mesh10.Offset = Vector3.new(0.02, -0.1, 0)
mesh10.Scale = Vector3.new(0.6, 1, 1)
mesh10.Parent = key11

key11.Parent = keyset4

local key12 = Instance.new("Part")
key12.Name = "Key12"
key12.Anchored = true
key12.BottomSurface = Enum.SurfaceType.Smooth
key12.BrickColor = BrickColor.White()
key12.CFrame = CFrame.new(8.69263554, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key12.CanCollide = false
key12.Color = Color3.fromRGB(242, 243, 243)
key12.Material = Enum.Material.SmoothPlastic
key12.Rotation = Vector3.new(-180, 0, -180)
key12.Size = Vector3.new(0.2, 0.2, 1.2)
key12.TopSurface = Enum.SurfaceType.Smooth

local mesh11 = Instance.new("BlockMesh")
mesh11.Name = "Mesh"
mesh11.Parent = key12

key12.Parent = keyset4

keyset4.Parent = keys

local keyset5 = Instance.new("Model")
keyset5.Name = "Keyset5"
keyset5.WorldPivot = CFrame.new(7.89258671, 0.2000103, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)

local key11 = Instance.new("Part")
key11.Name = "Key1"
key11.Anchored = true
key11.BottomSurface = Enum.SurfaceType.Smooth
key11.BrickColor = BrickColor.White()
key11.CFrame = CFrame.new(8.49253178, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key11.CanCollide = false
key11.Color = Color3.fromRGB(242, 243, 243)
key11.Material = Enum.Material.SmoothPlastic
key11.Rotation = Vector3.new(-180, 0, -180)
key11.Size = Vector3.new(0.2, 0.2, 1.2)
key11.TopSurface = Enum.SurfaceType.Smooth

local mesh12 = Instance.new("BlockMesh")
mesh12.Name = "Mesh"
mesh12.Parent = key11

key11.Parent = keyset5

local key21 = Instance.new("Part")
key21.Name = "Key2"
key21.Anchored = true
key21.BottomSurface = Enum.SurfaceType.Smooth
key21.BrickColor = BrickColor.new("Really black")
key21.CFrame = CFrame.new(8.39261627, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key21.CanCollide = false
key21.Color = Color3.fromRGB(17, 17, 17)
key21.Material = Enum.Material.SmoothPlastic
key21.Rotation = Vector3.new(-180, 0, -180)
key21.Size = Vector3.new(0.2, 0.2, 0.8)
key21.TopSurface = Enum.SurfaceType.Smooth

local mesh13 = Instance.new("BlockMesh")
mesh13.Name = "Mesh"
mesh13.Offset = Vector3.new(-0.02, -0.1, 0)
mesh13.Scale = Vector3.new(0.6, 1, 1)
mesh13.Parent = key21

key21.Parent = keyset5

local key31 = Instance.new("Part")
key31.Name = "Key3"
key31.Anchored = true
key31.BottomSurface = Enum.SurfaceType.Smooth
key31.BrickColor = BrickColor.White()
key31.CFrame = CFrame.new(8.29261112, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key31.CanCollide = false
key31.Color = Color3.fromRGB(242, 243, 243)
key31.Material = Enum.Material.SmoothPlastic
key31.Rotation = Vector3.new(-180, 0, -180)
key31.Size = Vector3.new(0.2, 0.2, 1.2)
key31.TopSurface = Enum.SurfaceType.Smooth

local mesh14 = Instance.new("BlockMesh")
mesh14.Name = "Mesh"
mesh14.Parent = key31

key31.Parent = keyset5

local key41 = Instance.new("Part")
key41.Name = "Key4"
key41.Anchored = true
key41.BottomSurface = Enum.SurfaceType.Smooth
key41.BrickColor = BrickColor.new("Really black")
key41.CFrame = CFrame.new(8.19260502, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key41.CanCollide = false
key41.Color = Color3.fromRGB(17, 17, 17)
key41.Material = Enum.Material.SmoothPlastic
key41.Rotation = Vector3.new(-180, 0, -180)
key41.Size = Vector3.new(0.2, 0.2, 0.8)
key41.TopSurface = Enum.SurfaceType.Smooth

local mesh15 = Instance.new("BlockMesh")
mesh15.Name = "Mesh"
mesh15.Offset = Vector3.new(0.02, -0.1, 0)
mesh15.Scale = Vector3.new(0.6, 1, 1)
mesh15.Parent = key41

key41.Parent = keyset5

local key51 = Instance.new("Part")
key51.Name = "Key5"
key51.Anchored = true
key51.BottomSurface = Enum.SurfaceType.Smooth
key51.BrickColor = BrickColor.White()
key51.CFrame = CFrame.new(8.0925684, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key51.CanCollide = false
key51.Color = Color3.fromRGB(242, 243, 243)
key51.Material = Enum.Material.SmoothPlastic
key51.Rotation = Vector3.new(-180, 0, -180)
key51.Size = Vector3.new(0.2, 0.2, 1.2)
key51.TopSurface = Enum.SurfaceType.Smooth

local mesh16 = Instance.new("BlockMesh")
mesh16.Name = "Mesh"
mesh16.Parent = key51

key51.Parent = keyset5

local key61 = Instance.new("Part")
key61.Name = "Key6"
key61.Anchored = true
key61.BottomSurface = Enum.SurfaceType.Smooth
key61.BrickColor = BrickColor.White()
key61.CFrame = CFrame.new(7.8925252, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key61.CanCollide = false
key61.Color = Color3.fromRGB(242, 243, 243)
key61.Material = Enum.Material.SmoothPlastic
key61.Rotation = Vector3.new(-180, 0, -180)
key61.Size = Vector3.new(0.2, 0.2, 1.2)
key61.TopSurface = Enum.SurfaceType.Smooth

local mesh17 = Instance.new("BlockMesh")
mesh17.Name = "Mesh"
mesh17.Parent = key61

key61.Parent = keyset5

local key71 = Instance.new("Part")
key71.Name = "Key7"
key71.Anchored = true
key71.BottomSurface = Enum.SurfaceType.Smooth
key71.BrickColor = BrickColor.new("Really black")
key71.CFrame = CFrame.new(7.79261112, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key71.CanCollide = false
key71.Color = Color3.fromRGB(17, 17, 17)
key71.Material = Enum.Material.SmoothPlastic
key71.Rotation = Vector3.new(-180, 0, -180)
key71.Size = Vector3.new(0.2, 0.2, 0.8)
key71.TopSurface = Enum.SurfaceType.Smooth

local mesh18 = Instance.new("BlockMesh")
mesh18.Name = "Mesh"
mesh18.Offset = Vector3.new(-0.02, -0.1, 0)
mesh18.Scale = Vector3.new(0.6, 1, 1)
mesh18.Parent = key71

key71.Parent = keyset5

local key81 = Instance.new("Part")
key81.Name = "Key8"
key81.Anchored = true
key81.BottomSurface = Enum.SurfaceType.Smooth
key81.BrickColor = BrickColor.White()
key81.CFrame = CFrame.new(7.69260502, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key81.CanCollide = false
key81.Color = Color3.fromRGB(242, 243, 243)
key81.Material = Enum.Material.SmoothPlastic
key81.Rotation = Vector3.new(-180, 0, -180)
key81.Size = Vector3.new(0.2, 0.2, 1.2)
key81.TopSurface = Enum.SurfaceType.Smooth

local mesh19 = Instance.new("BlockMesh")
mesh19.Name = "Mesh"
mesh19.Parent = key81

key81.Parent = keyset5

local key91 = Instance.new("Part")
key91.Name = "Key9"
key91.Anchored = true
key91.BottomSurface = Enum.SurfaceType.Smooth
key91.BrickColor = BrickColor.new("Really black")
key91.CFrame = CFrame.new(7.59262896, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key91.CanCollide = false
key91.Color = Color3.fromRGB(17, 17, 17)
key91.Material = Enum.Material.SmoothPlastic
key91.Rotation = Vector3.new(-180, 0, -180)
key91.Size = Vector3.new(0.2, 0.2, 0.8)
key91.TopSurface = Enum.SurfaceType.Smooth

local mesh20 = Instance.new("BlockMesh")
mesh20.Name = "Mesh"
mesh20.Offset = Vector3.new(0, -0.1, 0)
mesh20.Scale = Vector3.new(0.6, 1, 1)
mesh20.Parent = key91

key91.Parent = keyset5

local key101 = Instance.new("Part")
key101.Name = "Key10"
key101.Anchored = true
key101.BottomSurface = Enum.SurfaceType.Smooth
key101.BrickColor = BrickColor.White()
key101.CFrame = CFrame.new(7.49256182, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key101.CanCollide = false
key101.Color = Color3.fromRGB(242, 243, 243)
key101.Material = Enum.Material.SmoothPlastic
key101.Rotation = Vector3.new(-180, 0, -180)
key101.Size = Vector3.new(0.2, 0.2, 1.2)
key101.TopSurface = Enum.SurfaceType.Smooth

local mesh21 = Instance.new("BlockMesh")
mesh21.Name = "Mesh"
mesh21.Parent = key101

key101.Parent = keyset5

local key111 = Instance.new("Part")
key111.Name = "Key11"
key111.Anchored = true
key111.BottomSurface = Enum.SurfaceType.Smooth
key111.BrickColor = BrickColor.new("Really black")
key111.CFrame = CFrame.new(7.39255619, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key111.CanCollide = false
key111.Color = Color3.fromRGB(17, 17, 17)
key111.Material = Enum.Material.SmoothPlastic
key111.Rotation = Vector3.new(-180, 0, -180)
key111.Size = Vector3.new(0.2, 0.2, 0.8)
key111.TopSurface = Enum.SurfaceType.Smooth

local mesh22 = Instance.new("BlockMesh")
mesh22.Name = "Mesh"
mesh22.Offset = Vector3.new(0.02, -0.1, 0)
mesh22.Scale = Vector3.new(0.6, 1, 1)
mesh22.Parent = key111

key111.Parent = keyset5

local key121 = Instance.new("Part")
key121.Name = "Key12"
key121.Anchored = true
key121.BottomSurface = Enum.SurfaceType.Smooth
key121.BrickColor = BrickColor.White()
key121.CFrame = CFrame.new(7.29264116, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key121.CanCollide = false
key121.Color = Color3.fromRGB(242, 243, 243)
key121.Material = Enum.Material.SmoothPlastic
key121.Rotation = Vector3.new(-180, 0, -180)
key121.Size = Vector3.new(0.2, 0.2, 1.2)
key121.TopSurface = Enum.SurfaceType.Smooth

local mesh23 = Instance.new("BlockMesh")
mesh23.Name = "Mesh"
mesh23.Parent = key121

key121.Parent = keyset5

keyset5.Parent = keys

local keyset6 = Instance.new("Model")
keyset6.Name = "Keyset6"
keyset6.WorldPivot = CFrame.new(7.09259892, 0.100012779, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)

local key12 = Instance.new("Part")
key12.Name = "Key1"
key12.Anchored = true
key12.BottomSurface = Enum.SurfaceType.Smooth
key12.BrickColor = BrickColor.White()
key12.CFrame = CFrame.new(7.09259892, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key12.CanCollide = false
key12.Color = Color3.fromRGB(242, 243, 243)
key12.Material = Enum.Material.SmoothPlastic
key12.Rotation = Vector3.new(-180, 0, -180)
key12.Size = Vector3.new(0.2, 0.2, 1.2)
key12.TopSurface = Enum.SurfaceType.Smooth

local mesh24 = Instance.new("BlockMesh")
mesh24.Name = "Mesh"
mesh24.Parent = key12

key12.Parent = keyset6

keyset6.Parent = keys

local keyset1 = Instance.new("Model")
keyset1.Name = "Keyset1"
keyset1.WorldPivot = CFrame.new(13.4925623, 0.2000103, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)

local key22 = Instance.new("Part")
key22.Name = "Key2"
key22.Anchored = true
key22.BottomSurface = Enum.SurfaceType.Smooth
key22.BrickColor = BrickColor.new("Really black")
key22.CFrame = CFrame.new(13.9925623, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key22.CanCollide = false
key22.Color = Color3.fromRGB(17, 17, 17)
key22.Material = Enum.Material.SmoothPlastic
key22.Rotation = Vector3.new(-180, 0, -180)
key22.Size = Vector3.new(0.2, 0.2, 0.8)
key22.TopSurface = Enum.SurfaceType.Smooth

local mesh25 = Instance.new("BlockMesh")
mesh25.Name = "Mesh"
mesh25.Offset = Vector3.new(-0.02, -0.1, 0)
mesh25.Scale = Vector3.new(0.6, 1, 1)
mesh25.Parent = key22

key22.Parent = keyset1

local key32 = Instance.new("Part")
key32.Name = "Key3"
key32.Anchored = true
key32.BottomSurface = Enum.SurfaceType.Smooth
key32.BrickColor = BrickColor.White()
key32.CFrame = CFrame.new(13.8925858, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key32.CanCollide = false
key32.Color = Color3.fromRGB(242, 243, 243)
key32.Material = Enum.Material.SmoothPlastic
key32.Rotation = Vector3.new(-180, 0, -180)
key32.Size = Vector3.new(0.2, 0.2, 1.2)
key32.TopSurface = Enum.SurfaceType.Smooth

local mesh26 = Instance.new("BlockMesh")
mesh26.Name = "Mesh"
mesh26.Parent = key32

key32.Parent = keyset1

local key42 = Instance.new("Part")
key42.Name = "Key4"
key42.Anchored = true
key42.BottomSurface = Enum.SurfaceType.Smooth
key42.BrickColor = BrickColor.new("Really black")
key42.CFrame = CFrame.new(13.7925196, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key42.CanCollide = false
key42.Color = Color3.fromRGB(17, 17, 17)
key42.Material = Enum.Material.SmoothPlastic
key42.Rotation = Vector3.new(-180, 0, -180)
key42.Size = Vector3.new(0.2, 0.2, 0.8)
key42.TopSurface = Enum.SurfaceType.Smooth

local mesh27 = Instance.new("BlockMesh")
mesh27.Name = "Mesh"
mesh27.Offset = Vector3.new(0.02, -0.1, 0)
mesh27.Scale = Vector3.new(0.6, 1, 1)
mesh27.Parent = key42

key42.Parent = keyset1

local key52 = Instance.new("Part")
key52.Name = "Key5"
key52.Anchored = true
key52.BottomSurface = Enum.SurfaceType.Smooth
key52.BrickColor = BrickColor.White()
key52.CFrame = CFrame.new(13.692544, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key52.CanCollide = false
key52.Color = Color3.fromRGB(242, 243, 243)
key52.Material = Enum.Material.SmoothPlastic
key52.Rotation = Vector3.new(-180, 0, -180)
key52.Size = Vector3.new(0.2, 0.2, 1.2)
key52.TopSurface = Enum.SurfaceType.Smooth

local mesh28 = Instance.new("BlockMesh")
mesh28.Name = "Mesh"
mesh28.Parent = key52

key52.Parent = keyset1

local key62 = Instance.new("Part")
key62.Name = "Key6"
key62.Anchored = true
key62.BottomSurface = Enum.SurfaceType.Smooth
key62.BrickColor = BrickColor.White()
key62.CFrame = CFrame.new(13.4925318, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key62.CanCollide = false
key62.Color = Color3.fromRGB(242, 243, 243)
key62.Material = Enum.Material.SmoothPlastic
key62.Rotation = Vector3.new(-180, 0, -180)
key62.Size = Vector3.new(0.2, 0.2, 1.2)
key62.TopSurface = Enum.SurfaceType.Smooth

local mesh29 = Instance.new("BlockMesh")
mesh29.Name = "Mesh"
mesh29.Parent = key62

key62.Parent = keyset1

local key72 = Instance.new("Part")
key72.Name = "Key7"
key72.Anchored = true
key72.BottomSurface = Enum.SurfaceType.Smooth
key72.BrickColor = BrickColor.new("Really black")
key72.CFrame = CFrame.new(13.3925858, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key72.CanCollide = false
key72.Color = Color3.fromRGB(17, 17, 17)
key72.Material = Enum.Material.SmoothPlastic
key72.Rotation = Vector3.new(-180, 0, -180)
key72.Size = Vector3.new(0.2, 0.2, 0.8)
key72.TopSurface = Enum.SurfaceType.Smooth

local mesh30 = Instance.new("BlockMesh")
mesh30.Name = "Mesh"
mesh30.Offset = Vector3.new(-0.02, -0.1, 0)
mesh30.Scale = Vector3.new(0.6, 1, 1)
mesh30.Parent = key72

key72.Parent = keyset1

local key82 = Instance.new("Part")
key82.Name = "Key8"
key82.Anchored = true
key82.BottomSurface = Enum.SurfaceType.Smooth
key82.BrickColor = BrickColor.White()
key82.CFrame = CFrame.new(13.2925196, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key82.CanCollide = false
key82.Color = Color3.fromRGB(242, 243, 243)
key82.Material = Enum.Material.SmoothPlastic
key82.Rotation = Vector3.new(-180, 0, -180)
key82.Size = Vector3.new(0.2, 0.2, 1.2)
key82.TopSurface = Enum.SurfaceType.Smooth

local mesh31 = Instance.new("BlockMesh")
mesh31.Name = "Mesh"
mesh31.Parent = key82

key82.Parent = keyset1

local key92 = Instance.new("Part")
key92.Name = "Key9"
key92.Anchored = true
key92.BottomSurface = Enum.SurfaceType.Smooth
key92.BrickColor = BrickColor.new("Really black")
key92.CFrame = CFrame.new(13.192544, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key92.CanCollide = false
key92.Color = Color3.fromRGB(17, 17, 17)
key92.Material = Enum.Material.SmoothPlastic
key92.Rotation = Vector3.new(-180, 0, -180)
key92.Size = Vector3.new(0.2, 0.2, 0.8)
key92.TopSurface = Enum.SurfaceType.Smooth

local mesh32 = Instance.new("BlockMesh")
mesh32.Name = "Mesh"
mesh32.Offset = Vector3.new(0, -0.1, 0)
mesh32.Scale = Vector3.new(0.6, 1, 1)
mesh32.Parent = key92

key92.Parent = keyset1

local key102 = Instance.new("Part")
key102.Name = "Key10"
key102.Anchored = true
key102.BottomSurface = Enum.SurfaceType.Smooth
key102.BrickColor = BrickColor.White()
key102.CFrame = CFrame.new(13.0925379, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key102.CanCollide = false
key102.Color = Color3.fromRGB(242, 243, 243)
key102.Material = Enum.Material.SmoothPlastic
key102.Rotation = Vector3.new(-180, 0, -180)
key102.Size = Vector3.new(0.2, 0.2, 1.2)
key102.TopSurface = Enum.SurfaceType.Smooth

local mesh33 = Instance.new("BlockMesh")
mesh33.Name = "Mesh"
mesh33.Parent = key102

key102.Parent = keyset1

local key112 = Instance.new("Part")
key112.Name = "Key11"
key112.Anchored = true
key112.BottomSurface = Enum.SurfaceType.Smooth
key112.BrickColor = BrickColor.new("Really black")
key112.CFrame = CFrame.new(12.9925318, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key112.CanCollide = false
key112.Color = Color3.fromRGB(17, 17, 17)
key112.Material = Enum.Material.SmoothPlastic
key112.Rotation = Vector3.new(-180, 0, -180)
key112.Size = Vector3.new(0.2, 0.2, 0.8)
key112.TopSurface = Enum.SurfaceType.Smooth

local mesh34 = Instance.new("BlockMesh")
mesh34.Name = "Mesh"
mesh34.Offset = Vector3.new(0.02, -0.1, 0)
mesh34.Scale = Vector3.new(0.6, 1, 1)
mesh34.Parent = key112

key112.Parent = keyset1

local key122 = Instance.new("Part")
key122.Name = "Key12"
key122.Anchored = true
key122.BottomSurface = Enum.SurfaceType.Smooth
key122.BrickColor = BrickColor.White()
key122.CFrame = CFrame.new(12.8925858, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key122.CanCollide = false
key122.Color = Color3.fromRGB(242, 243, 243)
key122.Material = Enum.Material.SmoothPlastic
key122.Rotation = Vector3.new(-180, 0, -180)
key122.Size = Vector3.new(0.2, 0.2, 1.2)
key122.TopSurface = Enum.SurfaceType.Smooth

local mesh35 = Instance.new("BlockMesh")
mesh35.Name = "Mesh"
mesh35.Parent = key122

key122.Parent = keyset1

local key13 = Instance.new("Part")
key13.Name = "Key1"
key13.Anchored = true
key13.BottomSurface = Enum.SurfaceType.Smooth
key13.BrickColor = BrickColor.White()
key13.CFrame = CFrame.new(14.0925684, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key13.CanCollide = false
key13.Color = Color3.fromRGB(242, 243, 243)
key13.Material = Enum.Material.SmoothPlastic
key13.Rotation = Vector3.new(-180, 0, -180)
key13.Size = Vector3.new(0.2, 0.2, 1.2)
key13.TopSurface = Enum.SurfaceType.Smooth

local mesh36 = Instance.new("BlockMesh")
mesh36.Name = "Mesh"
mesh36.Parent = key13

key13.Parent = keyset1

keyset1.Parent = keys

local keyset3 = Instance.new("Model")
keyset3.Name = "Keyset3"
keyset3.WorldPivot = CFrame.new(10.692605, 0.2000103, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)

local key14 = Instance.new("Part")
key14.Name = "Key1"
key14.Anchored = true
key14.BottomSurface = Enum.SurfaceType.Smooth
key14.BrickColor = BrickColor.White()
key14.CFrame = CFrame.new(11.2926102, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key14.CanCollide = false
key14.Color = Color3.fromRGB(242, 243, 243)
key14.Material = Enum.Material.SmoothPlastic
key14.Rotation = Vector3.new(-180, 0, -180)
key14.Size = Vector3.new(0.2, 0.2, 1.2)
key14.TopSurface = Enum.SurfaceType.Smooth

local mesh37 = Instance.new("BlockMesh")
mesh37.Name = "Mesh"
mesh37.Parent = key14

key14.Parent = keyset3

local key23 = Instance.new("Part")
key23.Name = "Key2"
key23.Anchored = true
key23.BottomSurface = Enum.SurfaceType.Smooth
key23.BrickColor = BrickColor.new("Really black")
key23.CFrame = CFrame.new(11.1926041, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key23.CanCollide = false
key23.Color = Color3.fromRGB(17, 17, 17)
key23.Material = Enum.Material.SmoothPlastic
key23.Rotation = Vector3.new(-180, 0, -180)
key23.Size = Vector3.new(0.2, 0.2, 0.8)
key23.TopSurface = Enum.SurfaceType.Smooth

local mesh38 = Instance.new("BlockMesh")
mesh38.Name = "Mesh"
mesh38.Offset = Vector3.new(-0.02, -0.1, 0)
mesh38.Scale = Vector3.new(0.6, 1, 1)
mesh38.Parent = key23

key23.Parent = keyset3

local key33 = Instance.new("Part")
key33.Name = "Key3"
key33.Anchored = true
key33.BottomSurface = Enum.SurfaceType.Smooth
key33.BrickColor = BrickColor.White()
key33.CFrame = CFrame.new(11.092598, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key33.CanCollide = false
key33.Color = Color3.fromRGB(242, 243, 243)
key33.Material = Enum.Material.SmoothPlastic
key33.Rotation = Vector3.new(-180, 0, -180)
key33.Size = Vector3.new(0.2, 0.2, 1.2)
key33.TopSurface = Enum.SurfaceType.Smooth

local mesh39 = Instance.new("BlockMesh")
mesh39.Name = "Mesh"
mesh39.Parent = key33

key33.Parent = keyset3

local key43 = Instance.new("Part")
key43.Name = "Key4"
key43.Anchored = true
key43.BottomSurface = Enum.SurfaceType.Smooth
key43.BrickColor = BrickColor.new("Really black")
key43.CFrame = CFrame.new(10.9925318, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key43.CanCollide = false
key43.Color = Color3.fromRGB(17, 17, 17)
key43.Material = Enum.Material.SmoothPlastic
key43.Rotation = Vector3.new(-180, 0, -180)
key43.Size = Vector3.new(0.2, 0.2, 0.8)
key43.TopSurface = Enum.SurfaceType.Smooth

local mesh40 = Instance.new("BlockMesh")
mesh40.Name = "Mesh"
mesh40.Offset = Vector3.new(0.02, -0.1, 0)
mesh40.Scale = Vector3.new(0.6, 1, 1)
mesh40.Parent = key43

key43.Parent = keyset3

local key53 = Instance.new("Part")
key53.Name = "Key5"
key53.Anchored = true
key53.BottomSurface = Enum.SurfaceType.Smooth
key53.BrickColor = BrickColor.White()
key53.CFrame = CFrame.new(10.8925858, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key53.CanCollide = false
key53.Color = Color3.fromRGB(242, 243, 243)
key53.Material = Enum.Material.SmoothPlastic
key53.Rotation = Vector3.new(-180, 0, -180)
key53.Size = Vector3.new(0.2, 0.2, 1.2)
key53.TopSurface = Enum.SurfaceType.Smooth

local mesh41 = Instance.new("BlockMesh")
mesh41.Name = "Mesh"
mesh41.Parent = key53

key53.Parent = keyset3

local key63 = Instance.new("Part")
key63.Name = "Key6"
key63.Anchored = true
key63.BottomSurface = Enum.SurfaceType.Smooth
key63.BrickColor = BrickColor.White()
key63.CFrame = CFrame.new(10.6925735, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key63.CanCollide = false
key63.Color = Color3.fromRGB(242, 243, 243)
key63.Material = Enum.Material.SmoothPlastic
key63.Rotation = Vector3.new(-180, 0, -180)
key63.Size = Vector3.new(0.2, 0.2, 1.2)
key63.TopSurface = Enum.SurfaceType.Smooth

local mesh42 = Instance.new("BlockMesh")
mesh42.Name = "Mesh"
mesh42.Parent = key63

key63.Parent = keyset3

local key73 = Instance.new("Part")
key73.Name = "Key7"
key73.Anchored = true
key73.BottomSurface = Enum.SurfaceType.Smooth
key73.BrickColor = BrickColor.new("Really black")
key73.CFrame = CFrame.new(10.5925684, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key73.CanCollide = false
key73.Color = Color3.fromRGB(17, 17, 17)
key73.Material = Enum.Material.SmoothPlastic
key73.Rotation = Vector3.new(-180, 0, -180)
key73.Size = Vector3.new(0.2, 0.2, 0.8)
key73.TopSurface = Enum.SurfaceType.Smooth

local mesh43 = Instance.new("BlockMesh")
mesh43.Name = "Mesh"
mesh43.Offset = Vector3.new(-0.02, -0.1, 0)
mesh43.Scale = Vector3.new(0.6, 1, 1)
mesh43.Parent = key73

key73.Parent = keyset3

local key83 = Instance.new("Part")
key83.Name = "Key8"
key83.Anchored = true
key83.BottomSurface = Enum.SurfaceType.Smooth
key83.BrickColor = BrickColor.White()
key83.CFrame = CFrame.new(10.4925318, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key83.CanCollide = false
key83.Color = Color3.fromRGB(242, 243, 243)
key83.Material = Enum.Material.SmoothPlastic
key83.Rotation = Vector3.new(-180, 0, -180)
key83.Size = Vector3.new(0.2, 0.2, 1.2)
key83.TopSurface = Enum.SurfaceType.Smooth

local mesh44 = Instance.new("BlockMesh")
mesh44.Name = "Mesh"
mesh44.Parent = key83

key83.Parent = keyset3

local key93 = Instance.new("Part")
key93.Name = "Key9"
key93.Anchored = true
key93.BottomSurface = Enum.SurfaceType.Smooth
key93.BrickColor = BrickColor.new("Really black")
key93.CFrame = CFrame.new(10.3926163, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key93.CanCollide = false
key93.Color = Color3.fromRGB(17, 17, 17)
key93.Material = Enum.Material.SmoothPlastic
key93.Rotation = Vector3.new(-180, 0, -180)
key93.Size = Vector3.new(0.2, 0.2, 0.8)
key93.TopSurface = Enum.SurfaceType.Smooth

local mesh45 = Instance.new("BlockMesh")
mesh45.Name = "Mesh"
mesh45.Offset = Vector3.new(0, -0.1, 0)
mesh45.Scale = Vector3.new(0.6, 1, 1)
mesh45.Parent = key93

key93.Parent = keyset3

local key103 = Instance.new("Part")
key103.Name = "Key10"
key103.Anchored = true
key103.BottomSurface = Enum.SurfaceType.Smooth
key103.BrickColor = BrickColor.White()
key103.CFrame = CFrame.new(10.2926416, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key103.CanCollide = false
key103.Color = Color3.fromRGB(242, 243, 243)
key103.Material = Enum.Material.SmoothPlastic
key103.Rotation = Vector3.new(-180, 0, -180)
key103.Size = Vector3.new(0.2, 0.2, 1.2)
key103.TopSurface = Enum.SurfaceType.Smooth

local mesh46 = Instance.new("BlockMesh")
mesh46.Name = "Mesh"
mesh46.Parent = key103

key103.Parent = keyset3

local key113 = Instance.new("Part")
key113.Name = "Key11"
key113.Anchored = true
key113.BottomSurface = Enum.SurfaceType.Smooth
key113.BrickColor = BrickColor.new("Really black")
key113.CFrame = CFrame.new(10.1926041, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key113.CanCollide = false
key113.Color = Color3.fromRGB(17, 17, 17)
key113.Material = Enum.Material.SmoothPlastic
key113.Rotation = Vector3.new(-180, 0, -180)
key113.Size = Vector3.new(0.2, 0.2, 0.8)
key113.TopSurface = Enum.SurfaceType.Smooth

local mesh47 = Instance.new("BlockMesh")
mesh47.Name = "Mesh"
mesh47.Offset = Vector3.new(0.02, -0.1, 0)
mesh47.Scale = Vector3.new(0.6, 1, 1)
mesh47.Parent = key113

key113.Parent = keyset3

local key123 = Instance.new("Part")
key123.Name = "Key12"
key123.Anchored = true
key123.BottomSurface = Enum.SurfaceType.Smooth
key123.BrickColor = BrickColor.White()
key123.CFrame = CFrame.new(10.092598, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key123.CanCollide = false
key123.Color = Color3.fromRGB(242, 243, 243)
key123.Material = Enum.Material.SmoothPlastic
key123.Rotation = Vector3.new(-180, 0, -180)
key123.Size = Vector3.new(0.2, 0.2, 1.2)
key123.TopSurface = Enum.SurfaceType.Smooth

local mesh48 = Instance.new("BlockMesh")
mesh48.Name = "Mesh"
mesh48.Parent = key123

key123.Parent = keyset3

keyset3.Parent = keys

local keyset2 = Instance.new("Model")
keyset2.Name = "Keyset2"
keyset2.WorldPivot = CFrame.new(12.0925684, 0.2000103, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)

local key15 = Instance.new("Part")
key15.Name = "Key1"
key15.Anchored = true
key15.BottomSurface = Enum.SurfaceType.Smooth
key15.BrickColor = BrickColor.White()
key15.CFrame = CFrame.new(12.6926041, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key15.CanCollide = false
key15.Color = Color3.fromRGB(242, 243, 243)
key15.Material = Enum.Material.SmoothPlastic
key15.Rotation = Vector3.new(-180, 0, -180)
key15.Size = Vector3.new(0.2, 0.2, 1.2)
key15.TopSurface = Enum.SurfaceType.Smooth

local mesh49 = Instance.new("BlockMesh")
mesh49.Name = "Mesh"
mesh49.Parent = key15

key15.Parent = keyset2

local key24 = Instance.new("Part")
key24.Name = "Key2"
key24.Anchored = true
key24.BottomSurface = Enum.SurfaceType.Smooth
key24.BrickColor = BrickColor.new("Really black")
key24.CFrame = CFrame.new(12.5925684, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key24.CanCollide = false
key24.Color = Color3.fromRGB(17, 17, 17)
key24.Material = Enum.Material.SmoothPlastic
key24.Rotation = Vector3.new(-180, 0, -180)
key24.Size = Vector3.new(0.2, 0.2, 0.8)
key24.TopSurface = Enum.SurfaceType.Smooth

local mesh50 = Instance.new("BlockMesh")
mesh50.Name = "Mesh"
mesh50.Offset = Vector3.new(-0.02, -0.1, 0)
mesh50.Scale = Vector3.new(0.6, 1, 1)
mesh50.Parent = key24

key24.Parent = keyset2

local key34 = Instance.new("Part")
key34.Name = "Key3"
key34.Anchored = true
key34.BottomSurface = Enum.SurfaceType.Smooth
key34.BrickColor = BrickColor.White()
key34.CFrame = CFrame.new(12.4925318, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key34.CanCollide = false
key34.Color = Color3.fromRGB(242, 243, 243)
key34.Material = Enum.Material.SmoothPlastic
key34.Rotation = Vector3.new(-180, 0, -180)
key34.Size = Vector3.new(0.2, 0.2, 1.2)
key34.TopSurface = Enum.SurfaceType.Smooth

local mesh51 = Instance.new("BlockMesh")
mesh51.Name = "Mesh"
mesh51.Parent = key34

key34.Parent = keyset2

local key44 = Instance.new("Part")
key44.Name = "Key4"
key44.Anchored = true
key44.BottomSurface = Enum.SurfaceType.Smooth
key44.BrickColor = BrickColor.new("Really black")
key44.CFrame = CFrame.new(12.3925858, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key44.CanCollide = false
key44.Color = Color3.fromRGB(17, 17, 17)
key44.Material = Enum.Material.SmoothPlastic
key44.Rotation = Vector3.new(-180, 0, -180)
key44.Size = Vector3.new(0.2, 0.2, 0.8)
key44.TopSurface = Enum.SurfaceType.Smooth

local mesh52 = Instance.new("BlockMesh")
mesh52.Name = "Mesh"
mesh52.Offset = Vector3.new(0.02, -0.1, 0)
mesh52.Scale = Vector3.new(0.6, 1, 1)
mesh52.Parent = key44

key44.Parent = keyset2

local key54 = Instance.new("Part")
key54.Name = "Key5"
key54.Anchored = true
key54.BottomSurface = Enum.SurfaceType.Smooth
key54.BrickColor = BrickColor.White()
key54.CFrame = CFrame.new(12.2925501, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key54.CanCollide = false
key54.Color = Color3.fromRGB(242, 243, 243)
key54.Material = Enum.Material.SmoothPlastic
key54.Rotation = Vector3.new(-180, 0, -180)
key54.Size = Vector3.new(0.2, 0.2, 1.2)
key54.TopSurface = Enum.SurfaceType.Smooth

local mesh53 = Instance.new("BlockMesh")
mesh53.Name = "Mesh"
mesh53.Parent = key54

key54.Parent = keyset2

local key64 = Instance.new("Part")
key64.Name = "Key6"
key64.Anchored = true
key64.BottomSurface = Enum.SurfaceType.Smooth
key64.BrickColor = BrickColor.White()
key64.CFrame = CFrame.new(12.092598, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key64.CanCollide = false
key64.Color = Color3.fromRGB(242, 243, 243)
key64.Material = Enum.Material.SmoothPlastic
key64.Rotation = Vector3.new(-180, 0, -180)
key64.Size = Vector3.new(0.2, 0.2, 1.2)
key64.TopSurface = Enum.SurfaceType.Smooth

local mesh54 = Instance.new("BlockMesh")
mesh54.Name = "Mesh"
mesh54.Parent = key64

key64.Parent = keyset2

local key74 = Instance.new("Part")
key74.Name = "Key7"
key74.Anchored = true
key74.BottomSurface = Enum.SurfaceType.Smooth
key74.BrickColor = BrickColor.new("Really black")
key74.CFrame = CFrame.new(11.9925318, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key74.CanCollide = false
key74.Color = Color3.fromRGB(17, 17, 17)
key74.Material = Enum.Material.SmoothPlastic
key74.Rotation = Vector3.new(-180, 0, -180)
key74.Size = Vector3.new(0.2, 0.2, 0.8)
key74.TopSurface = Enum.SurfaceType.Smooth

local mesh55 = Instance.new("BlockMesh")
mesh55.Name = "Mesh"
mesh55.Offset = Vector3.new(-0.02, -0.1, 0)
mesh55.Scale = Vector3.new(0.6, 1, 1)
mesh55.Parent = key74

key74.Parent = keyset2

local key84 = Instance.new("Part")
key84.Name = "Key8"
key84.Anchored = true
key84.BottomSurface = Enum.SurfaceType.Smooth
key84.BrickColor = BrickColor.White()
key84.CFrame = CFrame.new(11.8925858, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key84.CanCollide = false
key84.Color = Color3.fromRGB(242, 243, 243)
key84.Material = Enum.Material.SmoothPlastic
key84.Rotation = Vector3.new(-180, 0, -180)
key84.Size = Vector3.new(0.2, 0.2, 1.2)
key84.TopSurface = Enum.SurfaceType.Smooth

local mesh56 = Instance.new("BlockMesh")
mesh56.Name = "Mesh"
mesh56.Parent = key84

key84.Parent = keyset2

local key94 = Instance.new("Part")
key94.Name = "Key9"
key94.Anchored = true
key94.BottomSurface = Enum.SurfaceType.Smooth
key94.BrickColor = BrickColor.new("Really black")
key94.CFrame = CFrame.new(11.7925501, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key94.CanCollide = false
key94.Color = Color3.fromRGB(17, 17, 17)
key94.Material = Enum.Material.SmoothPlastic
key94.Rotation = Vector3.new(-180, 0, -180)
key94.Size = Vector3.new(0.2, 0.2, 0.8)
key94.TopSurface = Enum.SurfaceType.Smooth

local mesh57 = Instance.new("BlockMesh")
mesh57.Name = "Mesh"
mesh57.Offset = Vector3.new(0, -0.1, 0)
mesh57.Scale = Vector3.new(0.6, 1, 1)
mesh57.Parent = key94

key94.Parent = keyset2

local key104 = Instance.new("Part")
key104.Name = "Key10"
key104.Anchored = true
key104.BottomSurface = Enum.SurfaceType.Smooth
key104.BrickColor = BrickColor.White()
key104.CFrame = CFrame.new(11.6925735, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key104.CanCollide = false
key104.Color = Color3.fromRGB(242, 243, 243)
key104.Material = Enum.Material.SmoothPlastic
key104.Rotation = Vector3.new(-180, 0, -180)
key104.Size = Vector3.new(0.2, 0.2, 1.2)
key104.TopSurface = Enum.SurfaceType.Smooth

local mesh58 = Instance.new("BlockMesh")
mesh58.Name = "Mesh"
mesh58.Parent = key104

key104.Parent = keyset2

local key114 = Instance.new("Part")
key114.Name = "Key11"
key114.Anchored = true
key114.BottomSurface = Enum.SurfaceType.Smooth
key114.BrickColor = BrickColor.new("Really black")
key114.CFrame = CFrame.new(11.5925379, 0.300002992, -52.0357857, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key114.CanCollide = false
key114.Color = Color3.fromRGB(17, 17, 17)
key114.Material = Enum.Material.SmoothPlastic
key114.Rotation = Vector3.new(-180, 0, -180)
key114.Size = Vector3.new(0.2, 0.2, 0.8)
key114.TopSurface = Enum.SurfaceType.Smooth

local mesh59 = Instance.new("BlockMesh")
mesh59.Name = "Mesh"
mesh59.Offset = Vector3.new(0.02, -0.1, 0)
mesh59.Scale = Vector3.new(0.6, 1, 1)
mesh59.Parent = key114

key114.Parent = keyset2

local key124 = Instance.new("Part")
key124.Name = "Key12"
key124.Anchored = true
key124.BottomSurface = Enum.SurfaceType.Smooth
key124.BrickColor = BrickColor.White()
key124.CFrame = CFrame.new(11.4925318, 0.100008003, -52.2357674, -1, 0, -8.74227766e-08, 0, 0.999999642, 0, 8.74227766e-08, 0, -1)
key124.CanCollide = false
key124.Color = Color3.fromRGB(242, 243, 243)
key124.Material = Enum.Material.SmoothPlastic
key124.Rotation = Vector3.new(-180, 0, -180)
key124.Size = Vector3.new(0.2, 0.2, 1.2)
key124.TopSurface = Enum.SurfaceType.Smooth

local mesh60 = Instance.new("BlockMesh")
mesh60.Name = "Mesh"
mesh60.Parent = key124

key124.Parent = keyset2

keyset2.Parent = keys

return keys
